export const GET_DATA = 'GET_DATA';
export const SET_POSITION = 'SET_POSITION';
export const RESET_DRAG_OBJECT = 'RESET_DRAG_OBJECT';
export const UPDATE_SELECTED_STATE = 'UPDATE_SELECTED_STATE';
export const SET_TABLE_OVER = 'SET_TABLE_OVER';